[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  _source = "https://www.netlify.com/blog/2020/04/07/creating-better-more-predictable-redirect-rules-for-spas/"
  _comments = "let client fully control routing | (assume) index load logic from ReactRouter > read UR > transform site"

[[redirects]]
  from = "/api/*"
  to = "https://back-728pm.netlify.app/api/:splat"
  status = 200
